### ISSUE TITLE
集群版本升级带来的问题

### ISSUE THREAD

**Issue by LeLi0912** [BGI-shenzhen/Reseqtools#3]
请问一下，集群版本升级会影响软件使用么？现在遇到了这样一个问题：集群版本升级后，软件无法运行，一致卡着，在升级之前还能很好运行；在升级后重新安装了软件，运行时依旧一致卡着，想请问一下这个怎么解决呢？
祝好！

**Comment by hewm2008** [comment]
你好  软件 是静态编译过的 就理不再依赖系统的库了，A :   你看看是不是其它软件也卡，  B：程序所在目录盘阵的其它软件也卡（cp aaa.pl 到iTools同一目录  然后 perl  它）;  若仅仅是iTools卡的话 那就有可能，但从原理上看就理当是你们系统其它原因影响才是
